production:
  cloud_name: "hjxk6op4p"
  api_key: "726875636796787"
  api_secret: "872dJALE3jIrHrxgmNwNi_h9CZQ"
development:
  cloud_name: "hjxk6op4p"
  api_key: "726875636796787"
  api_secret: "872dJALE3jIrHrxgmNwNi_h9CZQ"
